name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: executing remote ssh commandss
        uses: appleboy/ssh-action@v1
        with:
          host: 16.16.187.35
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd 100xdevs-ci-cd
            git pull
            npm install
            npm run build
            npm run start
